In [1]:
# Arrays in Python

import numpy as np

# Lets create a small one-dimensional array - vector:
v1 = np.array( [2,4,6] )

print(v1) # 3 elements: 2,4,6
print( v1[0] ) # first element (index = 0)
print( v1[1] ) # first element (index = 1)
print( v1[2] ) # first element (index = 2)

print('sum of elements')

print( v1[0] + v1[1] + v1[2] ) # sum of the vector elements

# You can do also some arithmetic operations (element-by-element mode):

print( v1+2 )
print( v1**2 )
v2 = 3*v1
print( v2 )

[2 4 6]
2
4
6
sum of elements
12
[4 6 8]
[ 4 16 36]
[ 6 12 18]


In [4]:


v1 = np.array( [2,4,6] )

# You can apply math functions from NumPy module,
# simply pass name of the array (vector) to a function:

print( np.log10(v1) ) # log10 of each v1 element

# Please note v1 vector is unchanged

print(v1)

# To save the results you can create new vector:
v2 = np.log10(v1)

print(v2)


[0.30103    0.60205999 0.77815125]
[2 4 6]
[0.30103    0.60205999 0.77815125]


In [6]:
#Sometimes is useful to create a series of values, to do so, you can use linspace() or arange() functions:


v1 = np.linspace(0, 10, 5)
# start = 0
# end = 10
# number of equally spaced values (N) = 5

print(v1)




[ 0.   2.5  5.   7.5 10. ]


In [11]:
v2 = np.linspace(-1, 1, 5)
# start = 0 end = 10 N = 5
print("v2=", v2) # -1 -0.5 0 0.5 1

v3 = np.linspace(-1,1) # default N=50
print("v3=", v3) # 50 equally spaced values are generated

v4 = np.arange(0, 10, 5) # 0 5
# start = 0 step = 5 end 10 (not included)
print("v4=", v4)

v5 = np.arange(0, 1, 0.25) # 0 0.25 0.5 0.75
# start = 0 step = 0.25 end 1 (not included)
print("v5=", v5)

# you should see content of five created vectors v1, v2, v3, v4 and v5 (inside square brackets []):


v2= [-1.  -0.5  0.   0.5  1. ]
v3= [-1.         -0.95918367 -0.91836735 -0.87755102 -0.83673469 -0.79591837
 -0.75510204 -0.71428571 -0.67346939 -0.63265306 -0.59183673 -0.55102041
 -0.51020408 -0.46938776 -0.42857143 -0.3877551  -0.34693878 -0.30612245
 -0.26530612 -0.2244898  -0.18367347 -0.14285714 -0.10204082 -0.06122449
 -0.02040816  0.02040816  0.06122449  0.10204082  0.14285714  0.18367347
  0.2244898   0.26530612  0.30612245  0.34693878  0.3877551   0.42857143
  0.46938776  0.51020408  0.55102041  0.59183673  0.63265306  0.67346939
  0.71428571  0.75510204  0.79591837  0.83673469  0.87755102  0.91836735
  0.95918367  1.        ]
v4= [0 5]
v5= [0.   0.25 0.5  0.75]


In [12]:
# Creation of array (matrix) 2x3 (2 columns, 3rows):

m1 = np.array([[10,20],[30,40],[50,60]])
print(m1)

# Addressing one element [row_index][column_index]:
print( m1[0][0] ) # 10 - a first element - first column & row
print( m1[1][1] ) # 40 - a second column & row



[[10 20]
 [30 40]
 [50 60]]
10
40


In [14]:
# Addressing selected column (colon means all elements):
print('columns')
print("first col:", m1[:,0] ) # a first column (vector!)
print("second col:", m1[:,1] ) # a second column (vector)

# and selected rows:
print('rows')
print( m1[0,:] ) # a first row (vector)
print( m1[1,:] ) # a second row (vector)
print( m1[-1,:] ) # the last one (3rd) (also vector)


columns
first col: [10 30 50]
second col: [20 40 60]
rows
[10 20]
[30 40]
[50 60]
